config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
    resources :comments
  end
  resources :users

  root 'homes#index'
  get 'about' => 'home#about'
  get 'category' => 'categories#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # admin page
  namespace :admin do
    root to: "articles#index"
    resources :articles
    resources :users
    resources :categories
  end

  #UploadsController
  post 'uploads' => 'uploads#create'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  # 如果文章删除的话，相关的评论也要删除
  has_many :comments, dependent: :destroy

  validates :content, :title, presence: true
  validates :title, uniqueness: true

  searchkick
end

Article.reindex

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout "admin"

  include AdminHelper
  before_action :admin_user, only: [:index]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end
end

app/controllers/articles_controller.rb
# coding: utf-8
class ArticlesController < ApplicationController
  include ArticlesHelper
  include ApplicationHelper

  #attr_accessor :category_id
  before_action :set_article, only: [:show, :edit, :update, :destroy]


  skip_before_action :authorize, only: [:index, :show]

  #before_action :authorize, only: [:new, :create, :destroy]
  #before_action :logged_in_user, only: [:new, :create, :destroy] # 只有登录才能删除用户

  # GET /articles
  # GET /articles.json
  def index
    #@tags = Article.group(:category_id).count

    if params[:query].present?
        @articles = Article.search(params[:query])
    else  
        @articles = Article.order('created_at').page(params[:page])
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = session[:user_id]

    respond_to do |format|
      if @article.save
        flash[:success] = "创建成功"
        format.html { redirect_to @article}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        flash[:success] = "修改成功"
        format.html { redirect_to @article}
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      flash[:danger] = "文章已删除"
      format.html { redirect_to admin_articles_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # 白名单
    def article_params
      params.require(:article).permit(:content, :user_id, :title, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def create_time(article)
    # article.created_at.strftime("%Y-%m-%d %H:%M:%S")
    article.created_at.strftime("%Y-%m-%d")
  end

  def edit_time(article)
    # article.updated_at.strftime("%Y-%m-%d %H:%M:%S")
    article.updated_at.strftime("%Y-%m-%d")
  end

  #def author(article)
  #  if article.present?
  #    User.find_by_id(article.user_id).name
  #  end
  #end

  #def md_to_text(article)
  #  html_doc = markdown(article.content)
  #  text = strip_tags(html_doc)
  #end
end

app/views/articles/_article.html.erb
<ul>
  <% cache article do %>
    <div class="card">
      <h3 class="card-header"><%= article.title %></h3>
      <h3>
        <%= truncate strip_tags(article.content), length: 80 %>
      </h3>
      <div id="text-right">
        <%= button_to '查看', article,
                      :method => :get, class: "btn btn-primary pull-right" %>
      </div>
      <div>
        <% if article.category.present? %>
          分类：<span class="badge badge-primary">
                        <%= article.category.name %>
                     </span>
        <% end %>
      </div>
      <p>最后修改时间: <%= edit_time(article) %></p>
      <p>作者： <%= article.user.name %></p>
    </div>
  <% end %>
</ul>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_with(model: article, local: true) do |f| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title, '标题' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :category_id, '标签' %>
        <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "选择一个分类"} %>

        <%= link_to  "新建分类",  new_category_path, remote: true %>
      </div>

      <div class="field">
        <%= f.label :content, "文章内容" %>
        <%= f.text_area :content, class: "ckeditor" %>
      </div>


      <div class="actions">
        <%= f.submit "保存文章", class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_search.html.erb
<% provide(:title, "查看文章") %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% provide(:title, "文章列表") %>

<!--文章列表模块-->
<div class="container">
  <div class="row">
    <div class="col-8">
      <ul>
        <% cache  @articles do %>
          <% @articles.each do |article| %>
            <% cache article do %>

              <div class="card">
                <h3 class="card-header"><%= article.title %></h3>
                <h3>
                  <%= truncate strip_tags(article.content), length: 80 %>
                </h3>
                <div id="text-right">
                  <%= button_to '查看', article,
                                :method => :get, class: "btn btn-primary pull-right" %>
                </div>
                <div>
                  <% if article.category.present? %>
                    分类：<span class="badge badge-primary">
                        <%= article.category.name %>
                     </span>
                  <% end %>
                </div>
                <p>最后修改时间: <%= edit_time(article) %></p>
                <p>作者： <%= article.user.name %></p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>

  </div>
</div>

<div class="article_paginate">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<% provide(:title, "新建文章") %>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<% provide(:title, "查看文章") %>

<p id="notice"><%= notice %></p>

<div id="article_navigation">
  <ul class="breadcrumb">
    <li>
      <%= link_to "返回文章列表", articles_path %>
    </li>
  </ul>
</div>

<div class="title">
  <span>
    <%= @article.title %>
  </span>
</div>


<div class="info">
  <span>
    作者：<%= @article.user.name %>
  </span>
  <span>
    时间：<%= edit_time(@article) %>
  </span>
<!--  <ul>-->
<!--    <li>作者：<%#= @article.user.name %> </li>-->
<!--    <li>时间：<%#= edit_time(@article) %> </li>-->
<!--  </ul>-->
</div>

<%= (@article.content).html_safe %>

<!--匿名用户不能看到-->
<div id="article_button">
  <% if logged_in? %>
    <%= button_to '修改文章', edit_article_path(article_id: @article.id),
                  :method => :get, class: "btn btn-info" %>

      <%= button_to '删除文章',  @article, :method => :delete, class: "btn btn-danger"%>
  <% end %>
</div>

<p>添加一个评论：</p>
<%= render @article.comments %>

<% if logged_in? %>
  <%= render 'comments/form' %>
<% end %>