config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
    resources :comments
  end
  resources :users

  root 'homes#index'
  get 'about' => 'home#about'
  get 'category' => 'categories#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # admin page
  namespace :admin do
    root to: "articles#index"
    resources :articles
    resources :users
    resources :categories
  end

  #UploadsController
  post 'uploads' => 'uploads#create'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"

  include AdminHelper
  before_action :admin_user, only: [:index]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).includes(:articles)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        flash[:success] = '分类添加成功'
        format.html { redirect_to new_article_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      flash[:success] = "删除成功！"
      format.html { redirect_to admin_categories_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<% provide(:title, "用户管理界面") %>

<table class="table">
  <thead>
  <tr>
    <th>序号</th>
    <th>标题名</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% cache @categories do %>
    <% @categories.each do |category| %>
      <% cache category do %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td><%= button_to '修改', edit_category_path(id: category.id), method: :get,
                            class: "btn btn-primary" %></td>
          <td><%= button_to '删除', category, method: :delete, data: {confirm: "你确定?"},
                            class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <%= will_paginate @categories, :container => false %>
</div>