config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
    resources :comments
  end
  resources :users

  root 'homes#index'
  get 'about' => 'home#about'
  get 'category' => 'categories#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # admin page
  namespace :admin do
    root to: "articles#index"
    resources :articles
    resources :users
    resources :categories
  end

  #UploadsController
  post 'uploads' => 'uploads#create'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"

  include AdminHelper
  before_action :admin_user, only: [:index]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).includes(:articles)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        flash[:success] = '分类添加成功'
        format.html { redirect_to new_article_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      flash[:success] = "删除成功！"
      format.html { redirect_to admin_categories_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to category.name, category %>
    <span class="badge badge-primary badge-pill">
        <%= category.articles.size %>
      </span>
  </li>
</ul>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "输入新的类名", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '提交', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/new.js.erb
var html = "<%= j(render('form', remote: true)) %>"
// bootbox 弹窗插件
bootbox.dialog({
    title: "新增分类",
    message: html
});

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<% @category.articles.each do |article| %>
    <%= link_to article.title, article_path(article.id) %>
<% end %>