config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
    resources :comments
  end
  resources :users

  root 'homes#index'
  get 'about' => 'home#about'
  get 'category' => 'categories#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # admin page
  namespace :admin do
    root to: "articles#index"
    resources :articles
    resources :users
    resources :categories
  end

  #UploadsController
  post 'uploads' => 'uploads#create'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-center">
      苏ICP备18039745号
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--导航区-->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to "JackLovel's blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "首页", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "新建文章", new_article_path, class: "nav-link" %>
      </li>

      <% if admin_user? %>
        <li class="nav-item">
          <%= link_to "管理", admin_root_path, class: "nav-link" %>
        </li>
      <% end %>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "个人空间", current_user, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "登出", logout_path, method: "delete", class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "登录", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "注册", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

    <%= form_tag root_path, :class => "form-inline mt-2 mt-md-0", method: :get do %>
      <%= text_field_tag :q, params[:q], placeholder: "请输入关键字", class: "form-control mr-sm-2" %>
      <%= submit_tag "搜索", name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/layouts/_side.html.erb
<div class="list-group">
   <a href="<%= admin_users_path %>" class="<%= href_active?("users") %>">用户管理</a> 
   <a href="<%= admin_articles_path %>" class="<%= href_active?("articles") %>">文章管理</a>
   <a href="<%= admin_categories_path %>" class="<%= href_active?("categories") %>">分类管理</a>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= favicon_link_tag image_path("favicon.ico") %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= controller.controller_name %>">
<%= render "layouts/header" %>
<!--主要内容-->
<div class="container">
  <% flash.each do |message_type, message | %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-2">
        <%= render "layouts/side" %>
      </div>
      <div class="col-10">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= favicon_link_tag image_path("favicon.ico") %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="<%= asset_path("/js/ckeditor.js", skip_pipeline: true) %>"></script>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= render "layouts/header" %>
    <!--主要内容-->
    <div class="container">
      <% flash.each do |message_type, message | %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>

    <script type="text/javascript" charset="utf-8">
        document.addEventListener('turbolinks:load', () => {
            ClassicEditor.create(document.querySelector('.ckeditor'), {
                simpleUpload: { uploadUrl: '/uploads' },
            })
        })
    </script>
  </body>
</html>